// Wire protocol between workers and the controller.
//
// Regenerate the Go code after editing with `make proto` (needs protoc,
// protoc-gen-go and protoc-gen-go-grpc). The generated files are committed so
// normal builds never need protoc.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: internal/clusterpb/cluster.proto

package clusterpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Stream int32

const (
	Stream_STREAM_UNSPECIFIED Stream = 0
	Stream_STDOUT             Stream = 1
	Stream_STDERR             Stream = 2
)

// Enum value maps for Stream.
var (
	Stream_name = map[int32]string{
		0: "STREAM_UNSPECIFIED",
		1: "STDOUT",
		2: "STDERR",
	}
	Stream_value = map[string]int32{
		"STREAM_UNSPECIFIED": 0,
		"STDOUT":             1,
		"STDERR":             2,
	}
)

func (x Stream) Enum() *Stream {
	p := new(Stream)
	*p = x
	return p
}

func (x Stream) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Stream) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_clusterpb_cluster_proto_enumTypes[0].Descriptor()
}

func (Stream) Type() protoreflect.EnumType {
	return &file_internal_clusterpb_cluster_proto_enumTypes[0]
}

func (x Stream) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Stream.Descriptor instead.
func (Stream) EnumDescriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{0}
}

type JoinResponse_Status int32

const (
	JoinResponse_STATUS_UNSPECIFIED JoinResponse_Status = 0
	JoinResponse_APPROVED           JoinResponse_Status = 1
	JoinResponse_PENDING            JoinResponse_Status = 2
)

// Enum value maps for JoinResponse_Status.
var (
	JoinResponse_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "APPROVED",
		2: "PENDING",
	}
	JoinResponse_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"APPROVED":           1,
		"PENDING":            2,
	}
)

func (x JoinResponse_Status) Enum() *JoinResponse_Status {
	p := new(JoinResponse_Status)
	*p = x
	return p
}

func (x JoinResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JoinResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_clusterpb_cluster_proto_enumTypes[1].Descriptor()
}

func (JoinResponse_Status) Type() protoreflect.EnumType {
	return &file_internal_clusterpb_cluster_proto_enumTypes[1]
}

func (x JoinResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JoinResponse_Status.Descriptor instead.
func (JoinResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{7, 0}
}

type TaskResult_Outcome int32

const (
	TaskResult_OUTCOME_UNSPECIFIED TaskResult_Outcome = 0
	TaskResult_EXITED              TaskResult_Outcome = 1 // process exited; see exit_code
	TaskResult_FAILED_TO_START     TaskResult_Outcome = 2 // e.g. command not found by the runner itself
	TaskResult_TIMED_OUT           TaskResult_Outcome = 3
	TaskResult_CANCELED            TaskResult_Outcome = 4
	TaskResult_LOST                TaskResult_Outcome = 5 // worker restarted mid-task; not the task's fault
)

// Enum value maps for TaskResult_Outcome.
var (
	TaskResult_Outcome_name = map[int32]string{
		0: "OUTCOME_UNSPECIFIED",
		1: "EXITED",
		2: "FAILED_TO_START",
		3: "TIMED_OUT",
		4: "CANCELED",
		5: "LOST",
	}
	TaskResult_Outcome_value = map[string]int32{
		"OUTCOME_UNSPECIFIED": 0,
		"EXITED":              1,
		"FAILED_TO_START":     2,
		"TIMED_OUT":           3,
		"CANCELED":            4,
		"LOST":                5,
	}
)

func (x TaskResult_Outcome) Enum() *TaskResult_Outcome {
	p := new(TaskResult_Outcome)
	*p = x
	return p
}

func (x TaskResult_Outcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskResult_Outcome) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_clusterpb_cluster_proto_enumTypes[2].Descriptor()
}

func (TaskResult_Outcome) Type() protoreflect.EnumType {
	return &file_internal_clusterpb_cluster_proto_enumTypes[2]
}

func (x TaskResult_Outcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskResult_Outcome.Descriptor instead.
func (TaskResult_Outcome) EnumDescriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{23, 0}
}

type DownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sha256        string                 `protobuf:"bytes,1,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *DownloadRequest) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *DownloadRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sha256        string                 `protobuf:"bytes,1,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadStatusRequest) Reset() {
	*x = UploadStatusRequest{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadStatusRequest) ProtoMessage() {}

func (x *UploadStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadStatusRequest.ProtoReflect.Descriptor instead.
func (*UploadStatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *UploadStatusRequest) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *UploadStatusRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type UploadStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Complete      bool                   `protobuf:"varint,1,opt,name=complete,proto3" json:"complete,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"` // bytes already received; continue from here
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadStatusResponse) Reset() {
	*x = UploadStatusResponse{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadStatusResponse) ProtoMessage() {}

func (x *UploadStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadStatusResponse.ProtoReflect.Descriptor instead.
func (*UploadStatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *UploadStatusResponse) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *UploadStatusResponse) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type UploadChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sha256        string                 `protobuf:"bytes,1,opt,name=sha256,proto3" json:"sha256,omitempty"`  // set on the first chunk
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`     // total size, first chunk
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"` // where data starts, first chunk
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadChunk) Reset() {
	*x = UploadChunk{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadChunk) ProtoMessage() {}

func (x *UploadChunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadChunk.ProtoReflect.Descriptor instead.
func (*UploadChunk) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{4}
}

func (x *UploadChunk) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *UploadChunk) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *UploadChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *UploadChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Complete      bool                   `protobuf:"varint,1,opt,name=complete,proto3" json:"complete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{5}
}

func (x *UploadResponse) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	CsrDer        []byte                 `protobuf:"bytes,2,opt,name=csr_der,json=csrDer,proto3" json:"csr_der,omitempty"` // PKCS#10 CSR signed by the worker's private key
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Location      string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Ephemeral     bool                   `protobuf:"varint,5,opt,name=ephemeral,proto3" json:"ephemeral,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{6}
}

func (x *JoinRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *JoinRequest) GetCsrDer() []byte {
	if x != nil {
		return x.CsrDer
	}
	return nil
}

func (x *JoinRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *JoinRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *JoinRequest) GetEphemeral() bool {
	if x != nil {
		return x.Ephemeral
	}
	return false
}

type JoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        JoinResponse_Status    `protobuf:"varint,1,opt,name=status,proto3,enum=cluster.v1.JoinResponse_Status" json:"status,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CertDer       []byte                 `protobuf:"bytes,3,opt,name=cert_der,json=certDer,proto3" json:"cert_der,omitempty"`         // node certificate, set when APPROVED
	CaCertDer     []byte                 `protobuf:"bytes,4,opt,name=ca_cert_der,json=caCertDer,proto3" json:"ca_cert_der,omitempty"` // controller CA certificate
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{7}
}

func (x *JoinResponse) GetStatus() JoinResponse_Status {
	if x != nil {
		return x.Status
	}
	return JoinResponse_STATUS_UNSPECIFIED
}

func (x *JoinResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *JoinResponse) GetCertDer() []byte {
	if x != nil {
		return x.CertDer
	}
	return nil
}

func (x *JoinResponse) GetCaCertDer() []byte {
	if x != nil {
		return x.CaCertDer
	}
	return nil
}

type WorkerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*WorkerMessage_Hello
	//	*WorkerMessage_Metrics
	//	*WorkerMessage_Pong
	//	*WorkerMessage_TaskStarted
	//	*WorkerMessage_Log
	//	*WorkerMessage_Result
	//	*WorkerMessage_Progress
	Msg           isWorkerMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMessage) Reset() {
	*x = WorkerMessage{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMessage) ProtoMessage() {}

func (x *WorkerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMessage.ProtoReflect.Descriptor instead.
func (*WorkerMessage) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{8}
}

func (x *WorkerMessage) GetMsg() isWorkerMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *WorkerMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *WorkerMessage) GetMetrics() *Metrics {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_Metrics); ok {
			return x.Metrics
		}
	}
	return nil
}

func (x *WorkerMessage) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *WorkerMessage) GetTaskStarted() *TaskStarted {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_TaskStarted); ok {
			return x.TaskStarted
		}
	}
	return nil
}

func (x *WorkerMessage) GetLog() *LogChunk {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_Log); ok {
			return x.Log
		}
	}
	return nil
}

func (x *WorkerMessage) GetResult() *TaskResult {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *WorkerMessage) GetProgress() *TaskProgress {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

type isWorkerMessage_Msg interface {
	isWorkerMessage_Msg()
}

type WorkerMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type WorkerMessage_Metrics struct {
	Metrics *Metrics `protobuf:"bytes,2,opt,name=metrics,proto3,oneof"`
}

type WorkerMessage_Pong struct {
	Pong *Pong `protobuf:"bytes,3,opt,name=pong,proto3,oneof"`
}

type WorkerMessage_TaskStarted struct {
	TaskStarted *TaskStarted `protobuf:"bytes,4,opt,name=task_started,json=taskStarted,proto3,oneof"`
}

type WorkerMessage_Log struct {
	Log *LogChunk `protobuf:"bytes,5,opt,name=log,proto3,oneof"`
}

type WorkerMessage_Result struct {
	Result *TaskResult `protobuf:"bytes,6,opt,name=result,proto3,oneof"`
}

type WorkerMessage_Progress struct {
	Progress *TaskProgress `protobuf:"bytes,7,opt,name=progress,proto3,oneof"`
}

func (*WorkerMessage_Hello) isWorkerMessage_Msg() {}

func (*WorkerMessage_Metrics) isWorkerMessage_Msg() {}

func (*WorkerMessage_Pong) isWorkerMessage_Msg() {}

func (*WorkerMessage_TaskStarted) isWorkerMessage_Msg() {}

func (*WorkerMessage_Log) isWorkerMessage_Msg() {}

func (*WorkerMessage_Result) isWorkerMessage_Msg() {}

func (*WorkerMessage_Progress) isWorkerMessage_Msg() {}

type ControllerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ControllerMessage_Welcome
	//	*ControllerMessage_Ping
	//	*ControllerMessage_Assign
	//	*ControllerMessage_Cancel
	//	*ControllerMessage_ResultAck
	Msg           isControllerMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControllerMessage) Reset() {
	*x = ControllerMessage{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerMessage) ProtoMessage() {}

func (x *ControllerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerMessage.ProtoReflect.Descriptor instead.
func (*ControllerMessage) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{9}
}

func (x *ControllerMessage) GetMsg() isControllerMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ControllerMessage) GetWelcome() *Welcome {
	if x != nil {
		if x, ok := x.Msg.(*ControllerMessage_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *ControllerMessage) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Msg.(*ControllerMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *ControllerMessage) GetAssign() *AssignTask {
	if x != nil {
		if x, ok := x.Msg.(*ControllerMessage_Assign); ok {
			return x.Assign
		}
	}
	return nil
}

func (x *ControllerMessage) GetCancel() *CancelTask {
	if x != nil {
		if x, ok := x.Msg.(*ControllerMessage_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

func (x *ControllerMessage) GetResultAck() *ResultAck {
	if x != nil {
		if x, ok := x.Msg.(*ControllerMessage_ResultAck); ok {
			return x.ResultAck
		}
	}
	return nil
}

type isControllerMessage_Msg interface {
	isControllerMessage_Msg()
}

type ControllerMessage_Welcome struct {
	Welcome *Welcome `protobuf:"bytes,1,opt,name=welcome,proto3,oneof"`
}

type ControllerMessage_Ping struct {
	Ping *Ping `protobuf:"bytes,2,opt,name=ping,proto3,oneof"`
}

type ControllerMessage_Assign struct {
	Assign *AssignTask `protobuf:"bytes,3,opt,name=assign,proto3,oneof"`
}

type ControllerMessage_Cancel struct {
	Cancel *CancelTask `protobuf:"bytes,4,opt,name=cancel,proto3,oneof"`
}

type ControllerMessage_ResultAck struct {
	ResultAck *ResultAck `protobuf:"bytes,5,opt,name=result_ack,json=resultAck,proto3,oneof"`
}

func (*ControllerMessage_Welcome) isControllerMessage_Msg() {}

func (*ControllerMessage_Ping) isControllerMessage_Msg() {}

func (*ControllerMessage_Assign) isControllerMessage_Msg() {}

func (*ControllerMessage_Cancel) isControllerMessage_Msg() {}

func (*ControllerMessage_ResultAck) isControllerMessage_Msg() {}

type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Hardware      *HardwareInfo          `protobuf:"bytes,2,opt,name=hardware,proto3" json:"hardware,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Ephemeral     bool                   `protobuf:"varint,4,opt,name=ephemeral,proto3" json:"ephemeral,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SharedStorage string                 `protobuf:"bytes,6,opt,name=shared_storage,json=sharedStorage,proto3" json:"shared_storage,omitempty"` // optional path shared with the controller/other nodes
	// Every attempt this worker still holds: running, still shipping logs, or
	// finished with a result not yet acknowledged. The controller adopts these
	// after a reconnect and treats any other attempt it placed here as lost.
	RunningAttempts []string `protobuf:"bytes,7,rep,name=running_attempts,json=runningAttempts,proto3" json:"running_attempts,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{10}
}

func (x *Hello) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Hello) GetHardware() *HardwareInfo {
	if x != nil {
		return x.Hardware
	}
	return nil
}

func (x *Hello) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Hello) GetEphemeral() bool {
	if x != nil {
		return x.Ephemeral
	}
	return false
}

func (x *Hello) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Hello) GetSharedStorage() string {
	if x != nil {
		return x.SharedStorage
	}
	return ""
}

func (x *Hello) GetRunningAttempts() []string {
	if x != nil {
		return x.RunningAttempts
	}
	return nil
}

type Welcome struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	NodeId                 string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	MetricsIntervalSeconds int32                  `protobuf:"varint,2,opt,name=metrics_interval_seconds,json=metricsIntervalSeconds,proto3" json:"metrics_interval_seconds,omitempty"`
	// How much of each adopted attempt's logs the controller already has, so
	// the worker resumes shipping from there.
	LogOffsets    map[string]*LogOffsets `protobuf:"bytes,3,rep,name=log_offsets,json=logOffsets,proto3" json:"log_offsets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{11}
}

func (x *Welcome) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Welcome) GetMetricsIntervalSeconds() int32 {
	if x != nil {
		return x.MetricsIntervalSeconds
	}
	return 0
}

func (x *Welcome) GetLogOffsets() map[string]*LogOffsets {
	if x != nil {
		return x.LogOffsets
	}
	return nil
}

type LogOffsets struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stdout        int64                  `protobuf:"varint,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        int64                  `protobuf:"varint,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogOffsets) Reset() {
	*x = LogOffsets{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogOffsets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogOffsets) ProtoMessage() {}

func (x *LogOffsets) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogOffsets.ProtoReflect.Descriptor instead.
func (*LogOffsets) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{12}
}

func (x *LogOffsets) GetStdout() int64 {
	if x != nil {
		return x.Stdout
	}
	return 0
}

func (x *LogOffsets) GetStderr() int64 {
	if x != nil {
		return x.Stderr
	}
	return 0
}

type GPUAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Vendor        string                 `protobuf:"bytes,3,opt,name=vendor,proto3" json:"vendor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPUAssignment) Reset() {
	*x = GPUAssignment{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUAssignment) ProtoMessage() {}

func (x *GPUAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUAssignment.ProtoReflect.Descriptor instead.
func (*GPUAssignment) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{13}
}

func (x *GPUAssignment) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *GPUAssignment) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GPUAssignment) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

// TaskSpec is everything a worker needs to run one attempt of a task.
type TaskSpec struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Command        string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"` // run with /bin/sh -c; {i} already substituted
	Env            map[string]string      `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Cpus           float64                `protobuf:"fixed64,3,opt,name=cpus,proto3" json:"cpus,omitempty"`
	MemoryBytes    uint64                 `protobuf:"varint,4,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"` // 0 = no limit
	Gpus           []*GPUAssignment       `protobuf:"bytes,5,rep,name=gpus,proto3" json:"gpus,omitempty"`
	TimeoutSeconds int64                  `protobuf:"varint,6,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"` // 0 = no timeout
	Inputs         []*InputFile           `protobuf:"bytes,7,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs        []string               `protobuf:"bytes,8,rep,name=outputs,proto3" json:"outputs,omitempty"` // globs relative to the working directory
	// image, if set, runs the task in a Docker container: the working
	// directory is mounted at /work, and command (if any) runs with
	// /bin/sh -c inside it; without a command the image's default runs.
	Image         string `protobuf:"bytes,9,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskSpec) Reset() {
	*x = TaskSpec{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSpec) ProtoMessage() {}

func (x *TaskSpec) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskSpec.ProtoReflect.Descriptor instead.
func (*TaskSpec) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{14}
}

func (x *TaskSpec) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *TaskSpec) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *TaskSpec) GetCpus() float64 {
	if x != nil {
		return x.Cpus
	}
	return 0
}

func (x *TaskSpec) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *TaskSpec) GetGpus() []*GPUAssignment {
	if x != nil {
		return x.Gpus
	}
	return nil
}

func (x *TaskSpec) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *TaskSpec) GetInputs() []*InputFile {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *TaskSpec) GetOutputs() []string {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *TaskSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

// InputFile is placed at path (relative to the task's working directory)
// before the task starts: downloaded by sha256, or, with shared_path,
// linked from the node's shared storage.
type InputFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Sha256        string                 `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Mode          uint32                 `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`
	SharedPath    string                 `protobuf:"bytes,5,opt,name=shared_path,json=sharedPath,proto3" json:"shared_path,omitempty"` // relative to the node's shared storage root
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputFile) Reset() {
	*x = InputFile{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputFile) ProtoMessage() {}

func (x *InputFile) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputFile.ProtoReflect.Descriptor instead.
func (*InputFile) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{15}
}

func (x *InputFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *InputFile) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *InputFile) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *InputFile) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *InputFile) GetSharedPath() string {
	if x != nil {
		return x.SharedPath
	}
	return ""
}

type OutputFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Sha256        string                 `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Mode          uint32                 `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputFile) Reset() {
	*x = OutputFile{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputFile) ProtoMessage() {}

func (x *OutputFile) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputFile.ProtoReflect.Descriptor instead.
func (*OutputFile) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{16}
}

func (x *OutputFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *OutputFile) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *OutputFile) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *OutputFile) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

// TaskProgress reports input download or output upload progress.
type TaskProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttemptId     string                 `protobuf:"bytes,1,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	Phase         string                 `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"` // "download" or "upload"
	DoneBytes     int64                  `protobuf:"varint,3,opt,name=done_bytes,json=doneBytes,proto3" json:"done_bytes,omitempty"`
	TotalBytes    int64                  `protobuf:"varint,4,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskProgress) Reset() {
	*x = TaskProgress{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskProgress) ProtoMessage() {}

func (x *TaskProgress) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskProgress.ProtoReflect.Descriptor instead.
func (*TaskProgress) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{17}
}

func (x *TaskProgress) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *TaskProgress) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *TaskProgress) GetDoneBytes() int64 {
	if x != nil {
		return x.DoneBytes
	}
	return 0
}

func (x *TaskProgress) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

type AssignTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttemptId     string                 `protobuf:"bytes,1,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	JobId         string                 `protobuf:"bytes,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Attempt       int32                  `protobuf:"varint,4,opt,name=attempt,proto3" json:"attempt,omitempty"` // 1 for the first attempt
	ArrayIndex    int64                  `protobuf:"varint,5,opt,name=array_index,json=arrayIndex,proto3" json:"array_index,omitempty"`
	Spec          *TaskSpec              `protobuf:"bytes,6,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignTask) Reset() {
	*x = AssignTask{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignTask) ProtoMessage() {}

func (x *AssignTask) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignTask.ProtoReflect.Descriptor instead.
func (*AssignTask) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{18}
}

func (x *AssignTask) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *AssignTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AssignTask) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *AssignTask) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *AssignTask) GetArrayIndex() int64 {
	if x != nil {
		return x.ArrayIndex
	}
	return 0
}

func (x *AssignTask) GetSpec() *TaskSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type CancelTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttemptId     string                 `protobuf:"bytes,1,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTask) Reset() {
	*x = CancelTask{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTask) ProtoMessage() {}

func (x *CancelTask) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTask.ProtoReflect.Descriptor instead.
func (*CancelTask) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{19}
}

func (x *CancelTask) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *CancelTask) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// ResultAck tells the worker it may delete its buffered result.
type ResultAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttemptId     string                 `protobuf:"bytes,1,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultAck) Reset() {
	*x = ResultAck{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultAck) ProtoMessage() {}

func (x *ResultAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultAck.ProtoReflect.Descriptor instead.
func (*ResultAck) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{20}
}

func (x *ResultAck) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

type TaskStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttemptId     string                 `protobuf:"bytes,1,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	StartedUnixMs int64                  `protobuf:"varint,2,opt,name=started_unix_ms,json=startedUnixMs,proto3" json:"started_unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStarted) Reset() {
	*x = TaskStarted{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStarted) ProtoMessage() {}

func (x *TaskStarted) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStarted.ProtoReflect.Descriptor instead.
func (*TaskStarted) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{21}
}

func (x *TaskStarted) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *TaskStarted) GetStartedUnixMs() int64 {
	if x != nil {
		return x.StartedUnixMs
	}
	return 0
}

type LogChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttemptId     string                 `protobuf:"bytes,1,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	Stream        Stream                 `protobuf:"varint,2,opt,name=stream,proto3,enum=cluster.v1.Stream" json:"stream,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"` // byte offset of data within the stream
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogChunk) Reset() {
	*x = LogChunk{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogChunk) ProtoMessage() {}

func (x *LogChunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogChunk.ProtoReflect.Descriptor instead.
func (*LogChunk) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{22}
}

func (x *LogChunk) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *LogChunk) GetStream() Stream {
	if x != nil {
		return x.Stream
	}
	return Stream_STREAM_UNSPECIFIED
}

func (x *LogChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *LogChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type TaskResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AttemptId      string                 `protobuf:"bytes,1,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	Outcome        TaskResult_Outcome     `protobuf:"varint,2,opt,name=outcome,proto3,enum=cluster.v1.TaskResult_Outcome" json:"outcome,omitempty"`
	ExitCode       int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Error          string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	StartedUnixMs  int64                  `protobuf:"varint,5,opt,name=started_unix_ms,json=startedUnixMs,proto3" json:"started_unix_ms,omitempty"`
	FinishedUnixMs int64                  `protobuf:"varint,6,opt,name=finished_unix_ms,json=finishedUnixMs,proto3" json:"finished_unix_ms,omitempty"`
	Outputs        []*OutputFile          `protobuf:"bytes,7,rep,name=outputs,proto3" json:"outputs,omitempty"` // already uploaded when the result is sent
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{23}
}

func (x *TaskResult) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *TaskResult) GetOutcome() TaskResult_Outcome {
	if x != nil {
		return x.Outcome
	}
	return TaskResult_OUTCOME_UNSPECIFIED
}

func (x *TaskResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *TaskResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TaskResult) GetStartedUnixMs() int64 {
	if x != nil {
		return x.StartedUnixMs
	}
	return 0
}

func (x *TaskResult) GetFinishedUnixMs() int64 {
	if x != nil {
		return x.FinishedUnixMs
	}
	return 0
}

func (x *TaskResult) GetOutputs() []*OutputFile {
	if x != nil {
		return x.Outputs
	}
	return nil
}

// Ping/Pong let the controller measure round-trip latency to each node.
type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         int64                  `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{24}
}

func (x *Ping) GetNonce() int64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         int64                  `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{25}
}

func (x *Pong) GetNonce() int64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type HardwareInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Kernel        string                 `protobuf:"bytes,3,opt,name=kernel,proto3" json:"kernel,omitempty"`
	Arch          string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	CpuModel      string                 `protobuf:"bytes,5,opt,name=cpu_model,json=cpuModel,proto3" json:"cpu_model,omitempty"`
	LogicalCores  int32                  `protobuf:"varint,6,opt,name=logical_cores,json=logicalCores,proto3" json:"logical_cores,omitempty"`
	PhysicalCores int32                  `protobuf:"varint,7,opt,name=physical_cores,json=physicalCores,proto3" json:"physical_cores,omitempty"`
	// Cores actually usable after any cgroup CPU quota (e.g. inside a vast.ai
	// container). Equals logical_cores when unlimited.
	CpuLimit float64 `protobuf:"fixed64,8,opt,name=cpu_limit,json=cpuLimit,proto3" json:"cpu_limit,omitempty"`
	// Usable RAM: the smaller of physical RAM and any cgroup memory limit.
	MemoryBytes   uint64   `protobuf:"varint,9,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	Disks         []*Disk  `protobuf:"bytes,10,rep,name=disks,proto3" json:"disks,omitempty"`
	Gpus          []*GPU   `protobuf:"bytes,11,rep,name=gpus,proto3" json:"gpus,omitempty"`
	InContainer   bool     `protobuf:"varint,12,opt,name=in_container,json=inContainer,proto3" json:"in_container,omitempty"`
	Docker        bool     `protobuf:"varint,13,opt,name=docker,proto3" json:"docker,omitempty"`                                 // docker CLI present and daemon reachable
	NvidiaDocker  bool     `protobuf:"varint,14,opt,name=nvidia_docker,json=nvidiaDocker,proto3" json:"nvidia_docker,omitempty"` // NVIDIA container toolkit usable with docker
	Systemd       bool     `protobuf:"varint,15,opt,name=systemd,proto3" json:"systemd,omitempty"`                               // systemd-run available for cgroup limits
	Ips           []string `protobuf:"bytes,16,rep,name=ips,proto3" json:"ips,omitempty"`
	BootTimeUnix  int64    `protobuf:"varint,17,opt,name=boot_time_unix,json=bootTimeUnix,proto3" json:"boot_time_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HardwareInfo) Reset() {
	*x = HardwareInfo{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HardwareInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardwareInfo) ProtoMessage() {}

func (x *HardwareInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardwareInfo.ProtoReflect.Descriptor instead.
func (*HardwareInfo) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{26}
}

func (x *HardwareInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *HardwareInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *HardwareInfo) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

func (x *HardwareInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *HardwareInfo) GetCpuModel() string {
	if x != nil {
		return x.CpuModel
	}
	return ""
}

func (x *HardwareInfo) GetLogicalCores() int32 {
	if x != nil {
		return x.LogicalCores
	}
	return 0
}

func (x *HardwareInfo) GetPhysicalCores() int32 {
	if x != nil {
		return x.PhysicalCores
	}
	return 0
}

func (x *HardwareInfo) GetCpuLimit() float64 {
	if x != nil {
		return x.CpuLimit
	}
	return 0
}

func (x *HardwareInfo) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *HardwareInfo) GetDisks() []*Disk {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *HardwareInfo) GetGpus() []*GPU {
	if x != nil {
		return x.Gpus
	}
	return nil
}

func (x *HardwareInfo) GetInContainer() bool {
	if x != nil {
		return x.InContainer
	}
	return false
}

func (x *HardwareInfo) GetDocker() bool {
	if x != nil {
		return x.Docker
	}
	return false
}

func (x *HardwareInfo) GetNvidiaDocker() bool {
	if x != nil {
		return x.NvidiaDocker
	}
	return false
}

func (x *HardwareInfo) GetSystemd() bool {
	if x != nil {
		return x.Systemd
	}
	return false
}

func (x *HardwareInfo) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

func (x *HardwareInfo) GetBootTimeUnix() int64 {
	if x != nil {
		return x.BootTimeUnix
	}
	return 0
}

type Disk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mount         string                 `protobuf:"bytes,1,opt,name=mount,proto3" json:"mount,omitempty"`
	Device        string                 `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	Fstype        string                 `protobuf:"bytes,3,opt,name=fstype,proto3" json:"fstype,omitempty"`
	TotalBytes    uint64                 `protobuf:"varint,4,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	FreeBytes     uint64                 `protobuf:"varint,5,opt,name=free_bytes,json=freeBytes,proto3" json:"free_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disk) Reset() {
	*x = Disk{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disk) ProtoMessage() {}

func (x *Disk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disk.ProtoReflect.Descriptor instead.
func (*Disk) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{27}
}

func (x *Disk) GetMount() string {
	if x != nil {
		return x.Mount
	}
	return ""
}

func (x *Disk) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *Disk) GetFstype() string {
	if x != nil {
		return x.Fstype
	}
	return ""
}

func (x *Disk) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *Disk) GetFreeBytes() uint64 {
	if x != nil {
		return x.FreeBytes
	}
	return 0
}

type GPU struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Vendor        string                 `protobuf:"bytes,2,opt,name=vendor,proto3" json:"vendor,omitempty"` // "nvidia" or "amd"
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Uuid          string                 `protobuf:"bytes,4,opt,name=uuid,proto3" json:"uuid,omitempty"`
	MemoryBytes   uint64                 `protobuf:"varint,5,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	Driver        string                 `protobuf:"bytes,6,opt,name=driver,proto3" json:"driver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPU) Reset() {
	*x = GPU{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPU) ProtoMessage() {}

func (x *GPU) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPU.ProtoReflect.Descriptor instead.
func (*GPU) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{28}
}

func (x *GPU) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *GPU) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *GPU) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GPU) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GPU) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *GPU) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

type Metrics struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TimeUnixMs       int64                  `protobuf:"varint,1,opt,name=time_unix_ms,json=timeUnixMs,proto3" json:"time_unix_ms,omitempty"`
	CpuPercent       float64                `protobuf:"fixed64,2,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	CpuPerCore       []float64              `protobuf:"fixed64,3,rep,packed,name=cpu_per_core,json=cpuPerCore,proto3" json:"cpu_per_core,omitempty"`
	MemUsedBytes     uint64                 `protobuf:"varint,4,opt,name=mem_used_bytes,json=memUsedBytes,proto3" json:"mem_used_bytes,omitempty"`
	MemTotalBytes    uint64                 `protobuf:"varint,5,opt,name=mem_total_bytes,json=memTotalBytes,proto3" json:"mem_total_bytes,omitempty"`
	Load1            float64                `protobuf:"fixed64,6,opt,name=load1,proto3" json:"load1,omitempty"`
	Load5            float64                `protobuf:"fixed64,7,opt,name=load5,proto3" json:"load5,omitempty"`
	Load15           float64                `protobuf:"fixed64,8,opt,name=load15,proto3" json:"load15,omitempty"`
	Disks            []*DiskUsage           `protobuf:"bytes,9,rep,name=disks,proto3" json:"disks,omitempty"`
	NetRxBytesPerSec uint64                 `protobuf:"varint,10,opt,name=net_rx_bytes_per_sec,json=netRxBytesPerSec,proto3" json:"net_rx_bytes_per_sec,omitempty"`
	NetTxBytesPerSec uint64                 `protobuf:"varint,11,opt,name=net_tx_bytes_per_sec,json=netTxBytesPerSec,proto3" json:"net_tx_bytes_per_sec,omitempty"`
	Gpus             []*GPUMetrics          `protobuf:"bytes,12,rep,name=gpus,proto3" json:"gpus,omitempty"`
	UptimeSeconds    uint64                 `protobuf:"varint,13,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{29}
}

func (x *Metrics) GetTimeUnixMs() int64 {
	if x != nil {
		return x.TimeUnixMs
	}
	return 0
}

func (x *Metrics) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *Metrics) GetCpuPerCore() []float64 {
	if x != nil {
		return x.CpuPerCore
	}
	return nil
}

func (x *Metrics) GetMemUsedBytes() uint64 {
	if x != nil {
		return x.MemUsedBytes
	}
	return 0
}

func (x *Metrics) GetMemTotalBytes() uint64 {
	if x != nil {
		return x.MemTotalBytes
	}
	return 0
}

func (x *Metrics) GetLoad1() float64 {
	if x != nil {
		return x.Load1
	}
	return 0
}

func (x *Metrics) GetLoad5() float64 {
	if x != nil {
		return x.Load5
	}
	return 0
}

func (x *Metrics) GetLoad15() float64 {
	if x != nil {
		return x.Load15
	}
	return 0
}

func (x *Metrics) GetDisks() []*DiskUsage {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *Metrics) GetNetRxBytesPerSec() uint64 {
	if x != nil {
		return x.NetRxBytesPerSec
	}
	return 0
}

func (x *Metrics) GetNetTxBytesPerSec() uint64 {
	if x != nil {
		return x.NetTxBytesPerSec
	}
	return 0
}

func (x *Metrics) GetGpus() []*GPUMetrics {
	if x != nil {
		return x.Gpus
	}
	return nil
}

func (x *Metrics) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type DiskUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mount         string                 `protobuf:"bytes,1,opt,name=mount,proto3" json:"mount,omitempty"`
	UsedBytes     uint64                 `protobuf:"varint,2,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	TotalBytes    uint64                 `protobuf:"varint,3,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskUsage) Reset() {
	*x = DiskUsage{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskUsage) ProtoMessage() {}

func (x *DiskUsage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskUsage.ProtoReflect.Descriptor instead.
func (*DiskUsage) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{30}
}

func (x *DiskUsage) GetMount() string {
	if x != nil {
		return x.Mount
	}
	return ""
}

func (x *DiskUsage) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *DiskUsage) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

type GPUMetrics struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Index              int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	UtilizationPercent float64                `protobuf:"fixed64,2,opt,name=utilization_percent,json=utilizationPercent,proto3" json:"utilization_percent,omitempty"`
	MemoryUsedBytes    uint64                 `protobuf:"varint,3,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	MemoryTotalBytes   uint64                 `protobuf:"varint,4,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	TemperatureC       float64                `protobuf:"fixed64,5,opt,name=temperature_c,json=temperatureC,proto3" json:"temperature_c,omitempty"`
	PowerWatts         float64                `protobuf:"fixed64,6,opt,name=power_watts,json=powerWatts,proto3" json:"power_watts,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GPUMetrics) Reset() {
	*x = GPUMetrics{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUMetrics) ProtoMessage() {}

func (x *GPUMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUMetrics.ProtoReflect.Descriptor instead.
func (*GPUMetrics) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{31}
}

func (x *GPUMetrics) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *GPUMetrics) GetUtilizationPercent() float64 {
	if x != nil {
		return x.UtilizationPercent
	}
	return 0
}

func (x *GPUMetrics) GetMemoryUsedBytes() uint64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *GPUMetrics) GetMemoryTotalBytes() uint64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

func (x *GPUMetrics) GetTemperatureC() float64 {
	if x != nil {
		return x.TemperatureC
	}
	return 0
}

func (x *GPUMetrics) GetPowerWatts() float64 {
	if x != nil {
		return x.PowerWatts
	}
	return 0
}

var File_internal_clusterpb_cluster_proto protoreflect.FileDescriptor

const file_internal_clusterpb_cluster_proto_rawDesc = "" +
	"\n" +
	" internal/clusterpb/cluster.proto\x12\n" +
	"cluster.v1\"A\n" +
	"\x0fDownloadRequest\x12\x16\n" +
	"\x06sha256\x18\x01 \x01(\tR\x06sha256\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"\x1f\n" +
	"\tFileChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"A\n" +
	"\x13UploadStatusRequest\x12\x16\n" +
	"\x06sha256\x18\x01 \x01(\tR\x06sha256\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\"J\n" +
	"\x14UploadStatusResponse\x12\x1a\n" +
	"\bcomplete\x18\x01 \x01(\bR\bcomplete\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"e\n" +
	"\vUploadChunk\x12\x16\n" +
	"\x06sha256\x18\x01 \x01(\tR\x06sha256\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\",\n" +
	"\x0eUploadResponse\x12\x1a\n" +
	"\bcomplete\x18\x01 \x01(\bR\bcomplete\"\x92\x01\n" +
	"\vJoinRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\acsr_der\x18\x02 \x01(\fR\x06csrDer\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12\x1c\n" +
	"\tephemeral\x18\x05 \x01(\bR\tephemeral\"\xd8\x01\n" +
	"\fJoinResponse\x127\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1f.cluster.v1.JoinResponse.StatusR\x06status\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x19\n" +
	"\bcert_der\x18\x03 \x01(\fR\acertDer\x12\x1e\n" +
	"\vca_cert_der\x18\x04 \x01(\fR\tcaCertDer\";\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bAPPROVED\x10\x01\x12\v\n" +
	"\aPENDING\x10\x02\"\xec\x02\n" +
	"\rWorkerMessage\x12)\n" +
	"\x05hello\x18\x01 \x01(\v2\x11.cluster.v1.HelloH\x00R\x05hello\x12/\n" +
	"\ametrics\x18\x02 \x01(\v2\x13.cluster.v1.MetricsH\x00R\ametrics\x12&\n" +
	"\x04pong\x18\x03 \x01(\v2\x10.cluster.v1.PongH\x00R\x04pong\x12<\n" +
	"\ftask_started\x18\x04 \x01(\v2\x17.cluster.v1.TaskStartedH\x00R\vtaskStarted\x12(\n" +
	"\x03log\x18\x05 \x01(\v2\x14.cluster.v1.LogChunkH\x00R\x03log\x120\n" +
	"\x06result\x18\x06 \x01(\v2\x16.cluster.v1.TaskResultH\x00R\x06result\x126\n" +
	"\bprogress\x18\a \x01(\v2\x18.cluster.v1.TaskProgressH\x00R\bprogressB\x05\n" +
	"\x03msg\"\x8f\x02\n" +
	"\x11ControllerMessage\x12/\n" +
	"\awelcome\x18\x01 \x01(\v2\x13.cluster.v1.WelcomeH\x00R\awelcome\x12&\n" +
	"\x04ping\x18\x02 \x01(\v2\x10.cluster.v1.PingH\x00R\x04ping\x120\n" +
	"\x06assign\x18\x03 \x01(\v2\x16.cluster.v1.AssignTaskH\x00R\x06assign\x120\n" +
	"\x06cancel\x18\x04 \x01(\v2\x16.cluster.v1.CancelTaskH\x00R\x06cancel\x126\n" +
	"\n" +
	"result_ack\x18\x05 \x01(\v2\x15.cluster.v1.ResultAckH\x00R\tresultAckB\x05\n" +
	"\x03msg\"\xd5\x02\n" +
	"\x05Hello\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x124\n" +
	"\bhardware\x18\x02 \x01(\v2\x18.cluster.v1.HardwareInfoR\bhardware\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12\x1c\n" +
	"\tephemeral\x18\x04 \x01(\bR\tephemeral\x125\n" +
	"\x06labels\x18\x05 \x03(\v2\x1d.cluster.v1.Hello.LabelsEntryR\x06labels\x12%\n" +
	"\x0eshared_storage\x18\x06 \x01(\tR\rsharedStorage\x12)\n" +
	"\x10running_attempts\x18\a \x03(\tR\x0frunningAttempts\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf9\x01\n" +
	"\aWelcome\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x128\n" +
	"\x18metrics_interval_seconds\x18\x02 \x01(\x05R\x16metricsIntervalSeconds\x12D\n" +
	"\vlog_offsets\x18\x03 \x03(\v2#.cluster.v1.Welcome.LogOffsetsEntryR\n" +
	"logOffsets\x1aU\n" +
	"\x0fLogOffsetsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.cluster.v1.LogOffsetsR\x05value:\x028\x01\"<\n" +
	"\n" +
	"LogOffsets\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\x03R\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x02 \x01(\x03R\x06stderr\"Q\n" +
	"\rGPUAssignment\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x16\n" +
	"\x06vendor\x18\x03 \x01(\tR\x06vendor\"\xfb\x02\n" +
	"\bTaskSpec\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12/\n" +
	"\x03env\x18\x02 \x03(\v2\x1d.cluster.v1.TaskSpec.EnvEntryR\x03env\x12\x12\n" +
	"\x04cpus\x18\x03 \x01(\x01R\x04cpus\x12!\n" +
	"\fmemory_bytes\x18\x04 \x01(\x04R\vmemoryBytes\x12-\n" +
	"\x04gpus\x18\x05 \x03(\v2\x19.cluster.v1.GPUAssignmentR\x04gpus\x12'\n" +
	"\x0ftimeout_seconds\x18\x06 \x01(\x03R\x0etimeoutSeconds\x12-\n" +
	"\x06inputs\x18\a \x03(\v2\x15.cluster.v1.InputFileR\x06inputs\x12\x18\n" +
	"\aoutputs\x18\b \x03(\tR\aoutputs\x12\x14\n" +
	"\x05image\x18\t \x01(\tR\x05image\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x80\x01\n" +
	"\tInputFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha256\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\rR\x04mode\x12\x1f\n" +
	"\vshared_path\x18\x05 \x01(\tR\n" +
	"sharedPath\"`\n" +
	"\n" +
	"OutputFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha256\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\rR\x04mode\"\x83\x01\n" +
	"\fTaskProgress\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x01 \x01(\tR\tattemptId\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12\x1d\n" +
	"\n" +
	"done_bytes\x18\x03 \x01(\x03R\tdoneBytes\x12\x1f\n" +
	"\vtotal_bytes\x18\x04 \x01(\x03R\n" +
	"totalBytes\"\xc0\x01\n" +
	"\n" +
	"AssignTask\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x01 \x01(\tR\tattemptId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x15\n" +
	"\x06job_id\x18\x03 \x01(\tR\x05jobId\x12\x18\n" +
	"\aattempt\x18\x04 \x01(\x05R\aattempt\x12\x1f\n" +
	"\varray_index\x18\x05 \x01(\x03R\n" +
	"arrayIndex\x12(\n" +
	"\x04spec\x18\x06 \x01(\v2\x14.cluster.v1.TaskSpecR\x04spec\"C\n" +
	"\n" +
	"CancelTask\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x01 \x01(\tR\tattemptId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"*\n" +
	"\tResultAck\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x01 \x01(\tR\tattemptId\"T\n" +
	"\vTaskStarted\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x01 \x01(\tR\tattemptId\x12&\n" +
	"\x0fstarted_unix_ms\x18\x02 \x01(\x03R\rstartedUnixMs\"\x81\x01\n" +
	"\bLogChunk\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x01 \x01(\tR\tattemptId\x12*\n" +
	"\x06stream\x18\x02 \x01(\x0e2\x12.cluster.v1.StreamR\x06stream\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"\x88\x03\n" +
	"\n" +
	"TaskResult\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x01 \x01(\tR\tattemptId\x128\n" +
	"\aoutcome\x18\x02 \x01(\x0e2\x1e.cluster.v1.TaskResult.OutcomeR\aoutcome\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12&\n" +
	"\x0fstarted_unix_ms\x18\x05 \x01(\x03R\rstartedUnixMs\x12(\n" +
	"\x10finished_unix_ms\x18\x06 \x01(\x03R\x0efinishedUnixMs\x120\n" +
	"\aoutputs\x18\a \x03(\v2\x16.cluster.v1.OutputFileR\aoutputs\"j\n" +
	"\aOutcome\x12\x17\n" +
	"\x13OUTCOME_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06EXITED\x10\x01\x12\x13\n" +
	"\x0fFAILED_TO_START\x10\x02\x12\r\n" +
	"\tTIMED_OUT\x10\x03\x12\f\n" +
	"\bCANCELED\x10\x04\x12\b\n" +
	"\x04LOST\x10\x05\"\x1c\n" +
	"\x04Ping\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x03R\x05nonce\"\x1c\n" +
	"\x04Pong\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x03R\x05nonce\"\x8e\x04\n" +
	"\fHardwareInfo\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x16\n" +
	"\x06kernel\x18\x03 \x01(\tR\x06kernel\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12\x1b\n" +
	"\tcpu_model\x18\x05 \x01(\tR\bcpuModel\x12#\n" +
	"\rlogical_cores\x18\x06 \x01(\x05R\flogicalCores\x12%\n" +
	"\x0ephysical_cores\x18\a \x01(\x05R\rphysicalCores\x12\x1b\n" +
	"\tcpu_limit\x18\b \x01(\x01R\bcpuLimit\x12!\n" +
	"\fmemory_bytes\x18\t \x01(\x04R\vmemoryBytes\x12&\n" +
	"\x05disks\x18\n" +
	" \x03(\v2\x10.cluster.v1.DiskR\x05disks\x12#\n" +
	"\x04gpus\x18\v \x03(\v2\x0f.cluster.v1.GPUR\x04gpus\x12!\n" +
	"\fin_container\x18\f \x01(\bR\vinContainer\x12\x16\n" +
	"\x06docker\x18\r \x01(\bR\x06docker\x12#\n" +
	"\rnvidia_docker\x18\x0e \x01(\bR\fnvidiaDocker\x12\x18\n" +
	"\asystemd\x18\x0f \x01(\bR\asystemd\x12\x10\n" +
	"\x03ips\x18\x10 \x03(\tR\x03ips\x12$\n" +
	"\x0eboot_time_unix\x18\x11 \x01(\x03R\fbootTimeUnix\"\x8c\x01\n" +
	"\x04Disk\x12\x14\n" +
	"\x05mount\x18\x01 \x01(\tR\x05mount\x12\x16\n" +
	"\x06device\x18\x02 \x01(\tR\x06device\x12\x16\n" +
	"\x06fstype\x18\x03 \x01(\tR\x06fstype\x12\x1f\n" +
	"\vtotal_bytes\x18\x04 \x01(\x04R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"free_bytes\x18\x05 \x01(\x04R\tfreeBytes\"\x96\x01\n" +
	"\x03GPU\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x16\n" +
	"\x06vendor\x18\x02 \x01(\tR\x06vendor\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04uuid\x18\x04 \x01(\tR\x04uuid\x12!\n" +
	"\fmemory_bytes\x18\x05 \x01(\x04R\vmemoryBytes\x12\x16\n" +
	"\x06driver\x18\x06 \x01(\tR\x06driver\"\xe0\x03\n" +
	"\aMetrics\x12 \n" +
	"\ftime_unix_ms\x18\x01 \x01(\x03R\n" +
	"timeUnixMs\x12\x1f\n" +
	"\vcpu_percent\x18\x02 \x01(\x01R\n" +
	"cpuPercent\x12 \n" +
	"\fcpu_per_core\x18\x03 \x03(\x01R\n" +
	"cpuPerCore\x12$\n" +
	"\x0emem_used_bytes\x18\x04 \x01(\x04R\fmemUsedBytes\x12&\n" +
	"\x0fmem_total_bytes\x18\x05 \x01(\x04R\rmemTotalBytes\x12\x14\n" +
	"\x05load1\x18\x06 \x01(\x01R\x05load1\x12\x14\n" +
	"\x05load5\x18\a \x01(\x01R\x05load5\x12\x16\n" +
	"\x06load15\x18\b \x01(\x01R\x06load15\x12+\n" +
	"\x05disks\x18\t \x03(\v2\x15.cluster.v1.DiskUsageR\x05disks\x12.\n" +
	"\x14net_rx_bytes_per_sec\x18\n" +
	" \x01(\x04R\x10netRxBytesPerSec\x12.\n" +
	"\x14net_tx_bytes_per_sec\x18\v \x01(\x04R\x10netTxBytesPerSec\x12*\n" +
	"\x04gpus\x18\f \x03(\v2\x16.cluster.v1.GPUMetricsR\x04gpus\x12%\n" +
	"\x0euptime_seconds\x18\r \x01(\x04R\ruptimeSeconds\"a\n" +
	"\tDiskUsage\x12\x14\n" +
	"\x05mount\x18\x01 \x01(\tR\x05mount\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x02 \x01(\x04R\tusedBytes\x12\x1f\n" +
	"\vtotal_bytes\x18\x03 \x01(\x04R\n" +
	"totalBytes\"\xf3\x01\n" +
	"\n" +
	"GPUMetrics\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12/\n" +
	"\x13utilization_percent\x18\x02 \x01(\x01R\x12utilizationPercent\x12*\n" +
	"\x11memory_used_bytes\x18\x03 \x01(\x04R\x0fmemoryUsedBytes\x12,\n" +
	"\x12memory_total_bytes\x18\x04 \x01(\x04R\x10memoryTotalBytes\x12#\n" +
	"\rtemperature_c\x18\x05 \x01(\x01R\ftemperatureC\x12\x1f\n" +
	"\vpower_watts\x18\x06 \x01(\x01R\n" +
	"powerWatts*8\n" +
	"\x06Stream\x12\x16\n" +
	"\x12STREAM_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06STDOUT\x10\x01\x12\n" +
	"\n" +
	"\x06STDERR\x10\x022\xe7\x02\n" +
	"\vNodeService\x129\n" +
	"\x04Join\x12\x17.cluster.v1.JoinRequest\x1a\x18.cluster.v1.JoinResponse\x12G\n" +
	"\aConnect\x12\x19.cluster.v1.WorkerMessage\x1a\x1d.cluster.v1.ControllerMessage(\x010\x01\x12@\n" +
	"\bDownload\x12\x1b.cluster.v1.DownloadRequest\x1a\x15.cluster.v1.FileChunk0\x01\x12Q\n" +
	"\fUploadStatus\x12\x1f.cluster.v1.UploadStatusRequest\x1a .cluster.v1.UploadStatusResponse\x12?\n" +
	"\x06Upload\x12\x17.cluster.v1.UploadChunk\x1a\x1a.cluster.v1.UploadResponse(\x01B<Z:github.com/NTFespolion307/QuorvexFusion/internal/clusterpbb\x06proto3"

var (
	file_internal_clusterpb_cluster_proto_rawDescOnce sync.Once
	file_internal_clusterpb_cluster_proto_rawDescData []byte
)

func file_internal_clusterpb_cluster_proto_rawDescGZIP() []byte {
	file_internal_clusterpb_cluster_proto_rawDescOnce.Do(func() {
		file_internal_clusterpb_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_clusterpb_cluster_proto_rawDesc), len(file_internal_clusterpb_cluster_proto_rawDesc)))
	})
	return file_internal_clusterpb_cluster_proto_rawDescData
}

var file_internal_clusterpb_cluster_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_internal_clusterpb_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_internal_clusterpb_cluster_proto_goTypes = []any{
	(Stream)(0),                  // 0: cluster.v1.Stream
	(JoinResponse_Status)(0),     // 1: cluster.v1.JoinResponse.Status
	(TaskResult_Outcome)(0),      // 2: cluster.v1.TaskResult.Outcome
	(*DownloadRequest)(nil),      // 3: cluster.v1.DownloadRequest
	(*FileChunk)(nil),            // 4: cluster.v1.FileChunk
	(*UploadStatusRequest)(nil),  // 5: cluster.v1.UploadStatusRequest
	(*UploadStatusResponse)(nil), // 6: cluster.v1.UploadStatusResponse
	(*UploadChunk)(nil),          // 7: cluster.v1.UploadChunk
	(*UploadResponse)(nil),       // 8: cluster.v1.UploadResponse
	(*JoinRequest)(nil),          // 9: cluster.v1.JoinRequest
	(*JoinResponse)(nil),         // 10: cluster.v1.JoinResponse
	(*WorkerMessage)(nil),        // 11: cluster.v1.WorkerMessage
	(*ControllerMessage)(nil),    // 12: cluster.v1.ControllerMessage
	(*Hello)(nil),                // 13: cluster.v1.Hello
	(*Welcome)(nil),              // 14: cluster.v1.Welcome
	(*LogOffsets)(nil),           // 15: cluster.v1.LogOffsets
	(*GPUAssignment)(nil),        // 16: cluster.v1.GPUAssignment
	(*TaskSpec)(nil),             // 17: cluster.v1.TaskSpec
	(*InputFile)(nil),            // 18: cluster.v1.InputFile
	(*OutputFile)(nil),           // 19: cluster.v1.OutputFile
	(*TaskProgress)(nil),         // 20: cluster.v1.TaskProgress
	(*AssignTask)(nil),           // 21: cluster.v1.AssignTask
	(*CancelTask)(nil),           // 22: cluster.v1.CancelTask
	(*ResultAck)(nil),            // 23: cluster.v1.ResultAck
	(*TaskStarted)(nil),          // 24: cluster.v1.TaskStarted
	(*LogChunk)(nil),             // 25: cluster.v1.LogChunk
	(*TaskResult)(nil),           // 26: cluster.v1.TaskResult
	(*Ping)(nil),                 // 27: cluster.v1.Ping
	(*Pong)(nil),                 // 28: cluster.v1.Pong
	(*HardwareInfo)(nil),         // 29: cluster.v1.HardwareInfo
	(*Disk)(nil),                 // 30: cluster.v1.Disk
	(*GPU)(nil),                  // 31: cluster.v1.GPU
	(*Metrics)(nil),              // 32: cluster.v1.Metrics
	(*DiskUsage)(nil),            // 33: cluster.v1.DiskUsage
	(*GPUMetrics)(nil),           // 34: cluster.v1.GPUMetrics
	nil,                          // 35: cluster.v1.Hello.LabelsEntry
	nil,                          // 36: cluster.v1.Welcome.LogOffsetsEntry
	nil,                          // 37: cluster.v1.TaskSpec.EnvEntry
}
var file_internal_clusterpb_cluster_proto_depIdxs = []int32{
	1,  // 0: cluster.v1.JoinResponse.status:type_name -> cluster.v1.JoinResponse.Status
	13, // 1: cluster.v1.WorkerMessage.hello:type_name -> cluster.v1.Hello
	32, // 2: cluster.v1.WorkerMessage.metrics:type_name -> cluster.v1.Metrics
	28, // 3: cluster.v1.WorkerMessage.pong:type_name -> cluster.v1.Pong
	24, // 4: cluster.v1.WorkerMessage.task_started:type_name -> cluster.v1.TaskStarted
	25, // 5: cluster.v1.WorkerMessage.log:type_name -> cluster.v1.LogChunk
	26, // 6: cluster.v1.WorkerMessage.result:type_name -> cluster.v1.TaskResult
	20, // 7: cluster.v1.WorkerMessage.progress:type_name -> cluster.v1.TaskProgress
	14, // 8: cluster.v1.ControllerMessage.welcome:type_name -> cluster.v1.Welcome
	27, // 9: cluster.v1.ControllerMessage.ping:type_name -> cluster.v1.Ping
	21, // 10: cluster.v1.ControllerMessage.assign:type_name -> cluster.v1.AssignTask
	22, // 11: cluster.v1.ControllerMessage.cancel:type_name -> cluster.v1.CancelTask
	23, // 12: cluster.v1.ControllerMessage.result_ack:type_name -> cluster.v1.ResultAck
	29, // 13: cluster.v1.Hello.hardware:type_name -> cluster.v1.HardwareInfo
	35, // 14: cluster.v1.Hello.labels:type_name -> cluster.v1.Hello.LabelsEntry
	36, // 15: cluster.v1.Welcome.log_offsets:type_name -> cluster.v1.Welcome.LogOffsetsEntry
	37, // 16: cluster.v1.TaskSpec.env:type_name -> cluster.v1.TaskSpec.EnvEntry
	16, // 17: cluster.v1.TaskSpec.gpus:type_name -> cluster.v1.GPUAssignment
	18, // 18: cluster.v1.TaskSpec.inputs:type_name -> cluster.v1.InputFile
	17, // 19: cluster.v1.AssignTask.spec:type_name -> cluster.v1.TaskSpec
	0,  // 20: cluster.v1.LogChunk.stream:type_name -> cluster.v1.Stream
	2,  // 21: cluster.v1.TaskResult.outcome:type_name -> cluster.v1.TaskResult.Outcome
	19, // 22: cluster.v1.TaskResult.outputs:type_name -> cluster.v1.OutputFile
	30, // 23: cluster.v1.HardwareInfo.disks:type_name -> cluster.v1.Disk
	31, // 24: cluster.v1.HardwareInfo.gpus:type_name -> cluster.v1.GPU
	33, // 25: cluster.v1.Metrics.disks:type_name -> cluster.v1.DiskUsage
	34, // 26: cluster.v1.Metrics.gpus:type_name -> cluster.v1.GPUMetrics
	15, // 27: cluster.v1.Welcome.LogOffsetsEntry.value:type_name -> cluster.v1.LogOffsets
	9,  // 28: cluster.v1.NodeService.Join:input_type -> cluster.v1.JoinRequest
	11, // 29: cluster.v1.NodeService.Connect:input_type -> cluster.v1.WorkerMessage
	3,  // 30: cluster.v1.NodeService.Download:input_type -> cluster.v1.DownloadRequest
	5,  // 31: cluster.v1.NodeService.UploadStatus:input_type -> cluster.v1.UploadStatusRequest
	7,  // 32: cluster.v1.NodeService.Upload:input_type -> cluster.v1.UploadChunk
	10, // 33: cluster.v1.NodeService.Join:output_type -> cluster.v1.JoinResponse
	12, // 34: cluster.v1.NodeService.Connect:output_type -> cluster.v1.ControllerMessage
	4,  // 35: cluster.v1.NodeService.Download:output_type -> cluster.v1.FileChunk
	6,  // 36: cluster.v1.NodeService.UploadStatus:output_type -> cluster.v1.UploadStatusResponse
	8,  // 37: cluster.v1.NodeService.Upload:output_type -> cluster.v1.UploadResponse
	33, // [33:38] is the sub-list for method output_type
	28, // [28:33] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_internal_clusterpb_cluster_proto_init() }
func file_internal_clusterpb_cluster_proto_init() {
	if File_internal_clusterpb_cluster_proto != nil {
		return
	}
	file_internal_clusterpb_cluster_proto_msgTypes[8].OneofWrappers = []any{
		(*WorkerMessage_Hello)(nil),
		(*WorkerMessage_Metrics)(nil),
		(*WorkerMessage_Pong)(nil),
		(*WorkerMessage_TaskStarted)(nil),
		(*WorkerMessage_Log)(nil),
		(*WorkerMessage_Result)(nil),
		(*WorkerMessage_Progress)(nil),
	}
	file_internal_clusterpb_cluster_proto_msgTypes[9].OneofWrappers = []any{
		(*ControllerMessage_Welcome)(nil),
		(*ControllerMessage_Ping)(nil),
		(*ControllerMessage_Assign)(nil),
		(*ControllerMessage_Cancel)(nil),
		(*ControllerMessage_ResultAck)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_clusterpb_cluster_proto_rawDesc), len(file_internal_clusterpb_cluster_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_clusterpb_cluster_proto_goTypes,
		DependencyIndexes: file_internal_clusterpb_cluster_proto_depIdxs,
		EnumInfos:         file_internal_clusterpb_cluster_proto_enumTypes,
		MessageInfos:      file_internal_clusterpb_cluster_proto_msgTypes,
	}.Build()
	File_internal_clusterpb_cluster_proto = out.File
	file_internal_clusterpb_cluster_proto_goTypes = nil
	file_internal_clusterpb_cluster_proto_depIdxs = nil
}
