// Wire protocol between workers and the controller.
//
// Regenerate the Go code after editing with `make proto` (needs protoc,
// protoc-gen-go and protoc-gen-go-grpc). The generated files are committed so
// normal builds never need protoc.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: internal/clusterpb/cluster.proto

package clusterpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinResponse_Status int32

const (
	JoinResponse_STATUS_UNSPECIFIED JoinResponse_Status = 0
	JoinResponse_APPROVED           JoinResponse_Status = 1
	JoinResponse_PENDING            JoinResponse_Status = 2
)

// Enum value maps for JoinResponse_Status.
var (
	JoinResponse_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "APPROVED",
		2: "PENDING",
	}
	JoinResponse_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"APPROVED":           1,
		"PENDING":            2,
	}
)

func (x JoinResponse_Status) Enum() *JoinResponse_Status {
	p := new(JoinResponse_Status)
	*p = x
	return p
}

func (x JoinResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JoinResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_clusterpb_cluster_proto_enumTypes[0].Descriptor()
}

func (JoinResponse_Status) Type() protoreflect.EnumType {
	return &file_internal_clusterpb_cluster_proto_enumTypes[0]
}

func (x JoinResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JoinResponse_Status.Descriptor instead.
func (JoinResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{1, 0}
}

type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	CsrDer        []byte                 `protobuf:"bytes,2,opt,name=csr_der,json=csrDer,proto3" json:"csr_der,omitempty"` // PKCS#10 CSR signed by the worker's private key
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Location      string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Ephemeral     bool                   `protobuf:"varint,5,opt,name=ephemeral,proto3" json:"ephemeral,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *JoinRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *JoinRequest) GetCsrDer() []byte {
	if x != nil {
		return x.CsrDer
	}
	return nil
}

func (x *JoinRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *JoinRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *JoinRequest) GetEphemeral() bool {
	if x != nil {
		return x.Ephemeral
	}
	return false
}

type JoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        JoinResponse_Status    `protobuf:"varint,1,opt,name=status,proto3,enum=cluster.v1.JoinResponse_Status" json:"status,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CertDer       []byte                 `protobuf:"bytes,3,opt,name=cert_der,json=certDer,proto3" json:"cert_der,omitempty"`         // node certificate, set when APPROVED
	CaCertDer     []byte                 `protobuf:"bytes,4,opt,name=ca_cert_der,json=caCertDer,proto3" json:"ca_cert_der,omitempty"` // controller CA certificate
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *JoinResponse) GetStatus() JoinResponse_Status {
	if x != nil {
		return x.Status
	}
	return JoinResponse_STATUS_UNSPECIFIED
}

func (x *JoinResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *JoinResponse) GetCertDer() []byte {
	if x != nil {
		return x.CertDer
	}
	return nil
}

func (x *JoinResponse) GetCaCertDer() []byte {
	if x != nil {
		return x.CaCertDer
	}
	return nil
}

type WorkerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*WorkerMessage_Hello
	//	*WorkerMessage_Metrics
	//	*WorkerMessage_Pong
	Msg           isWorkerMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMessage) Reset() {
	*x = WorkerMessage{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMessage) ProtoMessage() {}

func (x *WorkerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMessage.ProtoReflect.Descriptor instead.
func (*WorkerMessage) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *WorkerMessage) GetMsg() isWorkerMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *WorkerMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *WorkerMessage) GetMetrics() *Metrics {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_Metrics); ok {
			return x.Metrics
		}
	}
	return nil
}

func (x *WorkerMessage) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

type isWorkerMessage_Msg interface {
	isWorkerMessage_Msg()
}

type WorkerMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type WorkerMessage_Metrics struct {
	Metrics *Metrics `protobuf:"bytes,2,opt,name=metrics,proto3,oneof"`
}

type WorkerMessage_Pong struct {
	Pong *Pong `protobuf:"bytes,3,opt,name=pong,proto3,oneof"`
}

func (*WorkerMessage_Hello) isWorkerMessage_Msg() {}

func (*WorkerMessage_Metrics) isWorkerMessage_Msg() {}

func (*WorkerMessage_Pong) isWorkerMessage_Msg() {}

type ControllerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ControllerMessage_Welcome
	//	*ControllerMessage_Ping
	Msg           isControllerMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControllerMessage) Reset() {
	*x = ControllerMessage{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerMessage) ProtoMessage() {}

func (x *ControllerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerMessage.ProtoReflect.Descriptor instead.
func (*ControllerMessage) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *ControllerMessage) GetMsg() isControllerMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ControllerMessage) GetWelcome() *Welcome {
	if x != nil {
		if x, ok := x.Msg.(*ControllerMessage_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *ControllerMessage) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Msg.(*ControllerMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isControllerMessage_Msg interface {
	isControllerMessage_Msg()
}

type ControllerMessage_Welcome struct {
	Welcome *Welcome `protobuf:"bytes,1,opt,name=welcome,proto3,oneof"`
}

type ControllerMessage_Ping struct {
	Ping *Ping `protobuf:"bytes,2,opt,name=ping,proto3,oneof"`
}

func (*ControllerMessage_Welcome) isControllerMessage_Msg() {}

func (*ControllerMessage_Ping) isControllerMessage_Msg() {}

type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Hardware      *HardwareInfo          `protobuf:"bytes,2,opt,name=hardware,proto3" json:"hardware,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Ephemeral     bool                   `protobuf:"varint,4,opt,name=ephemeral,proto3" json:"ephemeral,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SharedStorage string                 `protobuf:"bytes,6,opt,name=shared_storage,json=sharedStorage,proto3" json:"shared_storage,omitempty"` // optional path shared with the controller/other nodes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{4}
}

func (x *Hello) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Hello) GetHardware() *HardwareInfo {
	if x != nil {
		return x.Hardware
	}
	return nil
}

func (x *Hello) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Hello) GetEphemeral() bool {
	if x != nil {
		return x.Ephemeral
	}
	return false
}

func (x *Hello) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Hello) GetSharedStorage() string {
	if x != nil {
		return x.SharedStorage
	}
	return ""
}

type Welcome struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	NodeId                 string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	MetricsIntervalSeconds int32                  `protobuf:"varint,2,opt,name=metrics_interval_seconds,json=metricsIntervalSeconds,proto3" json:"metrics_interval_seconds,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{5}
}

func (x *Welcome) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Welcome) GetMetricsIntervalSeconds() int32 {
	if x != nil {
		return x.MetricsIntervalSeconds
	}
	return 0
}

// Ping/Pong let the controller measure round-trip latency to each node.
type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         int64                  `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{6}
}

func (x *Ping) GetNonce() int64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         int64                  `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{7}
}

func (x *Pong) GetNonce() int64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type HardwareInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Kernel        string                 `protobuf:"bytes,3,opt,name=kernel,proto3" json:"kernel,omitempty"`
	Arch          string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	CpuModel      string                 `protobuf:"bytes,5,opt,name=cpu_model,json=cpuModel,proto3" json:"cpu_model,omitempty"`
	LogicalCores  int32                  `protobuf:"varint,6,opt,name=logical_cores,json=logicalCores,proto3" json:"logical_cores,omitempty"`
	PhysicalCores int32                  `protobuf:"varint,7,opt,name=physical_cores,json=physicalCores,proto3" json:"physical_cores,omitempty"`
	// Cores actually usable after any cgroup CPU quota (e.g. inside a vast.ai
	// container). Equals logical_cores when unlimited.
	CpuLimit float64 `protobuf:"fixed64,8,opt,name=cpu_limit,json=cpuLimit,proto3" json:"cpu_limit,omitempty"`
	// Usable RAM: the smaller of physical RAM and any cgroup memory limit.
	MemoryBytes   uint64   `protobuf:"varint,9,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	Disks         []*Disk  `protobuf:"bytes,10,rep,name=disks,proto3" json:"disks,omitempty"`
	Gpus          []*GPU   `protobuf:"bytes,11,rep,name=gpus,proto3" json:"gpus,omitempty"`
	InContainer   bool     `protobuf:"varint,12,opt,name=in_container,json=inContainer,proto3" json:"in_container,omitempty"`
	Docker        bool     `protobuf:"varint,13,opt,name=docker,proto3" json:"docker,omitempty"`                                 // docker CLI present and daemon reachable
	NvidiaDocker  bool     `protobuf:"varint,14,opt,name=nvidia_docker,json=nvidiaDocker,proto3" json:"nvidia_docker,omitempty"` // NVIDIA container toolkit usable with docker
	Systemd       bool     `protobuf:"varint,15,opt,name=systemd,proto3" json:"systemd,omitempty"`                               // systemd-run available for cgroup limits
	Ips           []string `protobuf:"bytes,16,rep,name=ips,proto3" json:"ips,omitempty"`
	BootTimeUnix  int64    `protobuf:"varint,17,opt,name=boot_time_unix,json=bootTimeUnix,proto3" json:"boot_time_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HardwareInfo) Reset() {
	*x = HardwareInfo{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HardwareInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardwareInfo) ProtoMessage() {}

func (x *HardwareInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardwareInfo.ProtoReflect.Descriptor instead.
func (*HardwareInfo) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{8}
}

func (x *HardwareInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *HardwareInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *HardwareInfo) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

func (x *HardwareInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *HardwareInfo) GetCpuModel() string {
	if x != nil {
		return x.CpuModel
	}
	return ""
}

func (x *HardwareInfo) GetLogicalCores() int32 {
	if x != nil {
		return x.LogicalCores
	}
	return 0
}

func (x *HardwareInfo) GetPhysicalCores() int32 {
	if x != nil {
		return x.PhysicalCores
	}
	return 0
}

func (x *HardwareInfo) GetCpuLimit() float64 {
	if x != nil {
		return x.CpuLimit
	}
	return 0
}

func (x *HardwareInfo) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *HardwareInfo) GetDisks() []*Disk {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *HardwareInfo) GetGpus() []*GPU {
	if x != nil {
		return x.Gpus
	}
	return nil
}

func (x *HardwareInfo) GetInContainer() bool {
	if x != nil {
		return x.InContainer
	}
	return false
}

func (x *HardwareInfo) GetDocker() bool {
	if x != nil {
		return x.Docker
	}
	return false
}

func (x *HardwareInfo) GetNvidiaDocker() bool {
	if x != nil {
		return x.NvidiaDocker
	}
	return false
}

func (x *HardwareInfo) GetSystemd() bool {
	if x != nil {
		return x.Systemd
	}
	return false
}

func (x *HardwareInfo) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

func (x *HardwareInfo) GetBootTimeUnix() int64 {
	if x != nil {
		return x.BootTimeUnix
	}
	return 0
}

type Disk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mount         string                 `protobuf:"bytes,1,opt,name=mount,proto3" json:"mount,omitempty"`
	Device        string                 `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	Fstype        string                 `protobuf:"bytes,3,opt,name=fstype,proto3" json:"fstype,omitempty"`
	TotalBytes    uint64                 `protobuf:"varint,4,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	FreeBytes     uint64                 `protobuf:"varint,5,opt,name=free_bytes,json=freeBytes,proto3" json:"free_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disk) Reset() {
	*x = Disk{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disk) ProtoMessage() {}

func (x *Disk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disk.ProtoReflect.Descriptor instead.
func (*Disk) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{9}
}

func (x *Disk) GetMount() string {
	if x != nil {
		return x.Mount
	}
	return ""
}

func (x *Disk) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *Disk) GetFstype() string {
	if x != nil {
		return x.Fstype
	}
	return ""
}

func (x *Disk) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *Disk) GetFreeBytes() uint64 {
	if x != nil {
		return x.FreeBytes
	}
	return 0
}

type GPU struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Vendor        string                 `protobuf:"bytes,2,opt,name=vendor,proto3" json:"vendor,omitempty"` // "nvidia" or "amd"
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Uuid          string                 `protobuf:"bytes,4,opt,name=uuid,proto3" json:"uuid,omitempty"`
	MemoryBytes   uint64                 `protobuf:"varint,5,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	Driver        string                 `protobuf:"bytes,6,opt,name=driver,proto3" json:"driver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPU) Reset() {
	*x = GPU{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPU) ProtoMessage() {}

func (x *GPU) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPU.ProtoReflect.Descriptor instead.
func (*GPU) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{10}
}

func (x *GPU) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *GPU) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *GPU) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GPU) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GPU) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *GPU) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

type Metrics struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TimeUnixMs       int64                  `protobuf:"varint,1,opt,name=time_unix_ms,json=timeUnixMs,proto3" json:"time_unix_ms,omitempty"`
	CpuPercent       float64                `protobuf:"fixed64,2,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	CpuPerCore       []float64              `protobuf:"fixed64,3,rep,packed,name=cpu_per_core,json=cpuPerCore,proto3" json:"cpu_per_core,omitempty"`
	MemUsedBytes     uint64                 `protobuf:"varint,4,opt,name=mem_used_bytes,json=memUsedBytes,proto3" json:"mem_used_bytes,omitempty"`
	MemTotalBytes    uint64                 `protobuf:"varint,5,opt,name=mem_total_bytes,json=memTotalBytes,proto3" json:"mem_total_bytes,omitempty"`
	Load1            float64                `protobuf:"fixed64,6,opt,name=load1,proto3" json:"load1,omitempty"`
	Load5            float64                `protobuf:"fixed64,7,opt,name=load5,proto3" json:"load5,omitempty"`
	Load15           float64                `protobuf:"fixed64,8,opt,name=load15,proto3" json:"load15,omitempty"`
	Disks            []*DiskUsage           `protobuf:"bytes,9,rep,name=disks,proto3" json:"disks,omitempty"`
	NetRxBytesPerSec uint64                 `protobuf:"varint,10,opt,name=net_rx_bytes_per_sec,json=netRxBytesPerSec,proto3" json:"net_rx_bytes_per_sec,omitempty"`
	NetTxBytesPerSec uint64                 `protobuf:"varint,11,opt,name=net_tx_bytes_per_sec,json=netTxBytesPerSec,proto3" json:"net_tx_bytes_per_sec,omitempty"`
	Gpus             []*GPUMetrics          `protobuf:"bytes,12,rep,name=gpus,proto3" json:"gpus,omitempty"`
	UptimeSeconds    uint64                 `protobuf:"varint,13,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{11}
}

func (x *Metrics) GetTimeUnixMs() int64 {
	if x != nil {
		return x.TimeUnixMs
	}
	return 0
}

func (x *Metrics) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *Metrics) GetCpuPerCore() []float64 {
	if x != nil {
		return x.CpuPerCore
	}
	return nil
}

func (x *Metrics) GetMemUsedBytes() uint64 {
	if x != nil {
		return x.MemUsedBytes
	}
	return 0
}

func (x *Metrics) GetMemTotalBytes() uint64 {
	if x != nil {
		return x.MemTotalBytes
	}
	return 0
}

func (x *Metrics) GetLoad1() float64 {
	if x != nil {
		return x.Load1
	}
	return 0
}

func (x *Metrics) GetLoad5() float64 {
	if x != nil {
		return x.Load5
	}
	return 0
}

func (x *Metrics) GetLoad15() float64 {
	if x != nil {
		return x.Load15
	}
	return 0
}

func (x *Metrics) GetDisks() []*DiskUsage {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *Metrics) GetNetRxBytesPerSec() uint64 {
	if x != nil {
		return x.NetRxBytesPerSec
	}
	return 0
}

func (x *Metrics) GetNetTxBytesPerSec() uint64 {
	if x != nil {
		return x.NetTxBytesPerSec
	}
	return 0
}

func (x *Metrics) GetGpus() []*GPUMetrics {
	if x != nil {
		return x.Gpus
	}
	return nil
}

func (x *Metrics) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type DiskUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mount         string                 `protobuf:"bytes,1,opt,name=mount,proto3" json:"mount,omitempty"`
	UsedBytes     uint64                 `protobuf:"varint,2,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	TotalBytes    uint64                 `protobuf:"varint,3,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskUsage) Reset() {
	*x = DiskUsage{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskUsage) ProtoMessage() {}

func (x *DiskUsage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskUsage.ProtoReflect.Descriptor instead.
func (*DiskUsage) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{12}
}

func (x *DiskUsage) GetMount() string {
	if x != nil {
		return x.Mount
	}
	return ""
}

func (x *DiskUsage) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *DiskUsage) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

type GPUMetrics struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Index              int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	UtilizationPercent float64                `protobuf:"fixed64,2,opt,name=utilization_percent,json=utilizationPercent,proto3" json:"utilization_percent,omitempty"`
	MemoryUsedBytes    uint64                 `protobuf:"varint,3,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	MemoryTotalBytes   uint64                 `protobuf:"varint,4,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	TemperatureC       float64                `protobuf:"fixed64,5,opt,name=temperature_c,json=temperatureC,proto3" json:"temperature_c,omitempty"`
	PowerWatts         float64                `protobuf:"fixed64,6,opt,name=power_watts,json=powerWatts,proto3" json:"power_watts,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GPUMetrics) Reset() {
	*x = GPUMetrics{}
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUMetrics) ProtoMessage() {}

func (x *GPUMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clusterpb_cluster_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUMetrics.ProtoReflect.Descriptor instead.
func (*GPUMetrics) Descriptor() ([]byte, []int) {
	return file_internal_clusterpb_cluster_proto_rawDescGZIP(), []int{13}
}

func (x *GPUMetrics) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *GPUMetrics) GetUtilizationPercent() float64 {
	if x != nil {
		return x.UtilizationPercent
	}
	return 0
}

func (x *GPUMetrics) GetMemoryUsedBytes() uint64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *GPUMetrics) GetMemoryTotalBytes() uint64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

func (x *GPUMetrics) GetTemperatureC() float64 {
	if x != nil {
		return x.TemperatureC
	}
	return 0
}

func (x *GPUMetrics) GetPowerWatts() float64 {
	if x != nil {
		return x.PowerWatts
	}
	return 0
}

var File_internal_clusterpb_cluster_proto protoreflect.FileDescriptor

const file_internal_clusterpb_cluster_proto_rawDesc = "" +
	"\n" +
	" internal/clusterpb/cluster.proto\x12\n" +
	"cluster.v1\"\x92\x01\n" +
	"\vJoinRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\acsr_der\x18\x02 \x01(\fR\x06csrDer\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12\x1c\n" +
	"\tephemeral\x18\x05 \x01(\bR\tephemeral\"\xd8\x01\n" +
	"\fJoinResponse\x127\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1f.cluster.v1.JoinResponse.StatusR\x06status\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x19\n" +
	"\bcert_der\x18\x03 \x01(\fR\acertDer\x12\x1e\n" +
	"\vca_cert_der\x18\x04 \x01(\fR\tcaCertDer\";\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bAPPROVED\x10\x01\x12\v\n" +
	"\aPENDING\x10\x02\"\x9a\x01\n" +
	"\rWorkerMessage\x12)\n" +
	"\x05hello\x18\x01 \x01(\v2\x11.cluster.v1.HelloH\x00R\x05hello\x12/\n" +
	"\ametrics\x18\x02 \x01(\v2\x13.cluster.v1.MetricsH\x00R\ametrics\x12&\n" +
	"\x04pong\x18\x03 \x01(\v2\x10.cluster.v1.PongH\x00R\x04pongB\x05\n" +
	"\x03msg\"s\n" +
	"\x11ControllerMessage\x12/\n" +
	"\awelcome\x18\x01 \x01(\v2\x13.cluster.v1.WelcomeH\x00R\awelcome\x12&\n" +
	"\x04ping\x18\x02 \x01(\v2\x10.cluster.v1.PingH\x00R\x04pingB\x05\n" +
	"\x03msg\"\xaa\x02\n" +
	"\x05Hello\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x124\n" +
	"\bhardware\x18\x02 \x01(\v2\x18.cluster.v1.HardwareInfoR\bhardware\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12\x1c\n" +
	"\tephemeral\x18\x04 \x01(\bR\tephemeral\x125\n" +
	"\x06labels\x18\x05 \x03(\v2\x1d.cluster.v1.Hello.LabelsEntryR\x06labels\x12%\n" +
	"\x0eshared_storage\x18\x06 \x01(\tR\rsharedStorage\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\\\n" +
	"\aWelcome\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x128\n" +
	"\x18metrics_interval_seconds\x18\x02 \x01(\x05R\x16metricsIntervalSeconds\"\x1c\n" +
	"\x04Ping\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x03R\x05nonce\"\x1c\n" +
	"\x04Pong\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x03R\x05nonce\"\x8e\x04\n" +
	"\fHardwareInfo\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x16\n" +
	"\x06kernel\x18\x03 \x01(\tR\x06kernel\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12\x1b\n" +
	"\tcpu_model\x18\x05 \x01(\tR\bcpuModel\x12#\n" +
	"\rlogical_cores\x18\x06 \x01(\x05R\flogicalCores\x12%\n" +
	"\x0ephysical_cores\x18\a \x01(\x05R\rphysicalCores\x12\x1b\n" +
	"\tcpu_limit\x18\b \x01(\x01R\bcpuLimit\x12!\n" +
	"\fmemory_bytes\x18\t \x01(\x04R\vmemoryBytes\x12&\n" +
	"\x05disks\x18\n" +
	" \x03(\v2\x10.cluster.v1.DiskR\x05disks\x12#\n" +
	"\x04gpus\x18\v \x03(\v2\x0f.cluster.v1.GPUR\x04gpus\x12!\n" +
	"\fin_container\x18\f \x01(\bR\vinContainer\x12\x16\n" +
	"\x06docker\x18\r \x01(\bR\x06docker\x12#\n" +
	"\rnvidia_docker\x18\x0e \x01(\bR\fnvidiaDocker\x12\x18\n" +
	"\asystemd\x18\x0f \x01(\bR\asystemd\x12\x10\n" +
	"\x03ips\x18\x10 \x03(\tR\x03ips\x12$\n" +
	"\x0eboot_time_unix\x18\x11 \x01(\x03R\fbootTimeUnix\"\x8c\x01\n" +
	"\x04Disk\x12\x14\n" +
	"\x05mount\x18\x01 \x01(\tR\x05mount\x12\x16\n" +
	"\x06device\x18\x02 \x01(\tR\x06device\x12\x16\n" +
	"\x06fstype\x18\x03 \x01(\tR\x06fstype\x12\x1f\n" +
	"\vtotal_bytes\x18\x04 \x01(\x04R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"free_bytes\x18\x05 \x01(\x04R\tfreeBytes\"\x96\x01\n" +
	"\x03GPU\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x16\n" +
	"\x06vendor\x18\x02 \x01(\tR\x06vendor\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04uuid\x18\x04 \x01(\tR\x04uuid\x12!\n" +
	"\fmemory_bytes\x18\x05 \x01(\x04R\vmemoryBytes\x12\x16\n" +
	"\x06driver\x18\x06 \x01(\tR\x06driver\"\xe0\x03\n" +
	"\aMetrics\x12 \n" +
	"\ftime_unix_ms\x18\x01 \x01(\x03R\n" +
	"timeUnixMs\x12\x1f\n" +
	"\vcpu_percent\x18\x02 \x01(\x01R\n" +
	"cpuPercent\x12 \n" +
	"\fcpu_per_core\x18\x03 \x03(\x01R\n" +
	"cpuPerCore\x12$\n" +
	"\x0emem_used_bytes\x18\x04 \x01(\x04R\fmemUsedBytes\x12&\n" +
	"\x0fmem_total_bytes\x18\x05 \x01(\x04R\rmemTotalBytes\x12\x14\n" +
	"\x05load1\x18\x06 \x01(\x01R\x05load1\x12\x14\n" +
	"\x05load5\x18\a \x01(\x01R\x05load5\x12\x16\n" +
	"\x06load15\x18\b \x01(\x01R\x06load15\x12+\n" +
	"\x05disks\x18\t \x03(\v2\x15.cluster.v1.DiskUsageR\x05disks\x12.\n" +
	"\x14net_rx_bytes_per_sec\x18\n" +
	" \x01(\x04R\x10netRxBytesPerSec\x12.\n" +
	"\x14net_tx_bytes_per_sec\x18\v \x01(\x04R\x10netTxBytesPerSec\x12*\n" +
	"\x04gpus\x18\f \x03(\v2\x16.cluster.v1.GPUMetricsR\x04gpus\x12%\n" +
	"\x0euptime_seconds\x18\r \x01(\x04R\ruptimeSeconds\"a\n" +
	"\tDiskUsage\x12\x14\n" +
	"\x05mount\x18\x01 \x01(\tR\x05mount\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x02 \x01(\x04R\tusedBytes\x12\x1f\n" +
	"\vtotal_bytes\x18\x03 \x01(\x04R\n" +
	"totalBytes\"\xf3\x01\n" +
	"\n" +
	"GPUMetrics\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12/\n" +
	"\x13utilization_percent\x18\x02 \x01(\x01R\x12utilizationPercent\x12*\n" +
	"\x11memory_used_bytes\x18\x03 \x01(\x04R\x0fmemoryUsedBytes\x12,\n" +
	"\x12memory_total_bytes\x18\x04 \x01(\x04R\x10memoryTotalBytes\x12#\n" +
	"\rtemperature_c\x18\x05 \x01(\x01R\ftemperatureC\x12\x1f\n" +
	"\vpower_watts\x18\x06 \x01(\x01R\n" +
	"powerWatts2\x91\x01\n" +
	"\vNodeService\x129\n" +
	"\x04Join\x12\x17.cluster.v1.JoinRequest\x1a\x18.cluster.v1.JoinResponse\x12G\n" +
	"\aConnect\x12\x19.cluster.v1.WorkerMessage\x1a\x1d.cluster.v1.ControllerMessage(\x010\x01B<Z:github.com/NTFespolion307/QuorvexFusion/internal/clusterpbb\x06proto3"

var (
	file_internal_clusterpb_cluster_proto_rawDescOnce sync.Once
	file_internal_clusterpb_cluster_proto_rawDescData []byte
)

func file_internal_clusterpb_cluster_proto_rawDescGZIP() []byte {
	file_internal_clusterpb_cluster_proto_rawDescOnce.Do(func() {
		file_internal_clusterpb_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_clusterpb_cluster_proto_rawDesc), len(file_internal_clusterpb_cluster_proto_rawDesc)))
	})
	return file_internal_clusterpb_cluster_proto_rawDescData
}

var file_internal_clusterpb_cluster_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_clusterpb_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_internal_clusterpb_cluster_proto_goTypes = []any{
	(JoinResponse_Status)(0),  // 0: cluster.v1.JoinResponse.Status
	(*JoinRequest)(nil),       // 1: cluster.v1.JoinRequest
	(*JoinResponse)(nil),      // 2: cluster.v1.JoinResponse
	(*WorkerMessage)(nil),     // 3: cluster.v1.WorkerMessage
	(*ControllerMessage)(nil), // 4: cluster.v1.ControllerMessage
	(*Hello)(nil),             // 5: cluster.v1.Hello
	(*Welcome)(nil),           // 6: cluster.v1.Welcome
	(*Ping)(nil),              // 7: cluster.v1.Ping
	(*Pong)(nil),              // 8: cluster.v1.Pong
	(*HardwareInfo)(nil),      // 9: cluster.v1.HardwareInfo
	(*Disk)(nil),              // 10: cluster.v1.Disk
	(*GPU)(nil),               // 11: cluster.v1.GPU
	(*Metrics)(nil),           // 12: cluster.v1.Metrics
	(*DiskUsage)(nil),         // 13: cluster.v1.DiskUsage
	(*GPUMetrics)(nil),        // 14: cluster.v1.GPUMetrics
	nil,                       // 15: cluster.v1.Hello.LabelsEntry
}
var file_internal_clusterpb_cluster_proto_depIdxs = []int32{
	0,  // 0: cluster.v1.JoinResponse.status:type_name -> cluster.v1.JoinResponse.Status
	5,  // 1: cluster.v1.WorkerMessage.hello:type_name -> cluster.v1.Hello
	12, // 2: cluster.v1.WorkerMessage.metrics:type_name -> cluster.v1.Metrics
	8,  // 3: cluster.v1.WorkerMessage.pong:type_name -> cluster.v1.Pong
	6,  // 4: cluster.v1.ControllerMessage.welcome:type_name -> cluster.v1.Welcome
	7,  // 5: cluster.v1.ControllerMessage.ping:type_name -> cluster.v1.Ping
	9,  // 6: cluster.v1.Hello.hardware:type_name -> cluster.v1.HardwareInfo
	15, // 7: cluster.v1.Hello.labels:type_name -> cluster.v1.Hello.LabelsEntry
	10, // 8: cluster.v1.HardwareInfo.disks:type_name -> cluster.v1.Disk
	11, // 9: cluster.v1.HardwareInfo.gpus:type_name -> cluster.v1.GPU
	13, // 10: cluster.v1.Metrics.disks:type_name -> cluster.v1.DiskUsage
	14, // 11: cluster.v1.Metrics.gpus:type_name -> cluster.v1.GPUMetrics
	1,  // 12: cluster.v1.NodeService.Join:input_type -> cluster.v1.JoinRequest
	3,  // 13: cluster.v1.NodeService.Connect:input_type -> cluster.v1.WorkerMessage
	2,  // 14: cluster.v1.NodeService.Join:output_type -> cluster.v1.JoinResponse
	4,  // 15: cluster.v1.NodeService.Connect:output_type -> cluster.v1.ControllerMessage
	14, // [14:16] is the sub-list for method output_type
	12, // [12:14] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_internal_clusterpb_cluster_proto_init() }
func file_internal_clusterpb_cluster_proto_init() {
	if File_internal_clusterpb_cluster_proto != nil {
		return
	}
	file_internal_clusterpb_cluster_proto_msgTypes[2].OneofWrappers = []any{
		(*WorkerMessage_Hello)(nil),
		(*WorkerMessage_Metrics)(nil),
		(*WorkerMessage_Pong)(nil),
	}
	file_internal_clusterpb_cluster_proto_msgTypes[3].OneofWrappers = []any{
		(*ControllerMessage_Welcome)(nil),
		(*ControllerMessage_Ping)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_clusterpb_cluster_proto_rawDesc), len(file_internal_clusterpb_cluster_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_clusterpb_cluster_proto_goTypes,
		DependencyIndexes: file_internal_clusterpb_cluster_proto_depIdxs,
		EnumInfos:         file_internal_clusterpb_cluster_proto_enumTypes,
		MessageInfos:      file_internal_clusterpb_cluster_proto_msgTypes,
	}.Build()
	File_internal_clusterpb_cluster_proto = out.File
	file_internal_clusterpb_cluster_proto_goTypes = nil
	file_internal_clusterpb_cluster_proto_depIdxs = nil
}
